spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    hikari:
      pool-name: mysql/ds1
      connection-timeout: 45000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 0
      connection-test-query: "select 1"
      validation-timeout: 1000
      isolate-internal-queries: true
  cloud:
    gateway:
      enabled: true
      default-filters:
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
#        - id: cloud-auth
#          uri: lb://cloud-auth
#          order: 0
#          predicates:
#            - Path=/auth/**
#          filters:
#            - StripPrefix=1
        - id: cloud-store
          uri: lb://cloud-store
          predicates:
            - Path=/store/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
#              - name:
#                args:
#                  key-resolver: #{@remoteAddressResolver}
#                  #令牌桶每秒填充平均速率
#                  redis-rate-limiter.replenishRate: 1
#                  #令牌桶容量
#                  redis-rate-limiter.burstCapacity: 5
#        - id: cloud-stream
#          uri: lb://cloud-stream
#          predicates:
#            - Path=/stream/**
#          filters:
#            - StripPrefix=1
#            - name:
#              args:
#                key-resolver:
#                #令牌桶每秒填充平均速率
#                redis-rate-limiter.replenishRate: 1
#                #令牌桶容量
#                redis-rate-limiter.burstCapacity: 5
#        - id: cloud-sleuth
#          uri: http://localhost:8083/**
#          predicates:
#            - Path=/cloud-sleuth/**
#        - id: after_route
#          uri: http://192.168.1.1
#          predicates:
#            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
#              - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
#              - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#              - Cookie=chocolate, ch.p
#              - Header=X-Request-Id, \d+
#              - Host=localhost
#              - Method=GET
#              - Path=/foo/{segment}
#              - Query=foo, ba.
#              - RemoteAddr=192.168.1.1/24
#          filters:
#            - AddRequestHeader=X-Request-Foo, Bar
#            - AddRequestParameter=foo, bar
#            - AddResponseHeader=X-Response-Foo, Bar
#            - Hystrix=myCommandName
  security:
    user:
      name: admin
      password: admin
  redis:
    jedis:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 0
        max-wait: 5000ms
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000ms
