spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    hikari:
      pool-name: mysql/ds1
      connection-timeout: 45000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 0
      connection-test-query: "select 1"
      validation-timeout: 1000
      isolate-internal-queries: true
  cloud:
    gateway:
      enabled: true
      routes:
        - id: after_route
          uri: http://192.168.1.1
          predicates:
            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
            - Cookie=chocolate, ch.p
            - Header=X-Request-Id, \d+
            - Host=localhost
            - Method=GET
            - Path=/foo/{segment}
            - Query=foo, ba.
            - RemoteAddr=192.168.1.1/24
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
            - AddRequestParameter=foo, bar
            - AddResponseHeader=X-Response-Foo, Bar
            - Hystrix=myCommandName
        - id: ingredients-fallback
          uri: http://localhost:9994
          predicates:
            - Path=/fallback
  security:
    user:
      name: admin
      password: admin